export { default as DepartmentDashboardPage } from './DepartmentDashboardPage'
export { getDepartmentDashboardNavItems, isRescueDepartment } from './departmentDashboardConfig'
export type { DepartmentDashboardNavItem, DepartmentDashboardSectionKey } from './departmentDashboardConfig'
export { default as DepartmentBottomNav } from './DepartmentBottomNav'
export { default as DepartmentHomeSection } from './DepartmentHomeSection'
export { default as DepartmentScannerSection } from './DepartmentScannerSection'
export { default as DepartmentRequestsSection } from './DepartmentRequestsSection'
export { default as DepartmentReportsSection } from './DepartmentReportsSection'
export { default as DepartmentProfileSection } from './DepartmentProfileSection'
